<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="BoxService"
        targetNamespace="http://boxservice.example.com/"
        xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
        xmlns:tns="http://boxservice.example.com/"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:types>
        <xsd:schema attributeFormDefault="unqualified" elementFormDefault="unqualified"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                targetNamespace="http://boxservice.example.com/"
                xmlns:tns="http://boxservice.example.com/">
            <xsd:element name="checkBoxFree" type="tns:checkBoxFree"/>
            
                <xsd:complexType name="checkBoxFree">
                	<xsd:sequence>
                		<xsd:element name="box" type="xsd:string" />
                	</xsd:sequence>
                </xsd:complexType>
            
            <xsd:element name="checkBoxFreeResponse">
            	<xsd:complexType>
            		<xsd:sequence>
            			<xsd:element name="response" type="xsd:boolean" />
            		</xsd:sequence>
            	</xsd:complexType>
            </xsd:element>
		</xsd:schema>
	</wsdl:types>
	
	<wsdl:message name="checkBoxFree">
		<wsdl:part name="parameters" element="tns:checkBoxFree"/>
	</wsdl:message>
	<wsdl:message name="checkBoxFreeResponse">
		<wsdl:part name="parameters" element="tns:checkBoxFreeResponse"/>
	</wsdl:message>
	<wsdl:portType name="BoxService">
<!-- 		<jaxws:bindings xmlns:jaxws="http://java.sun.com/xml/ns/jaxws">
        	<jaxws:enableWrapperStyle>true</jaxws:enableWrapperStyle>
        </jaxws:bindings>  -->
		<wsdl:operation name="checkBoxFree">
			<wsdl:input name="checkBoxFree" message="tns:checkBoxFree"/>
			<wsdl:output name="checkBoxFreeResponse" message="tns:checkBoxFreeResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="BoxServiceSoapBinding"
		type="tns:BoxService">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="checkBoxFree">
			<soap:operation soapAction="" style="document" />
			<wsdl:input name="checkBoxFree">
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output name="checkBoxFreeResponse">
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="BoxService">
		<wsdl:port name="BoxServicePort" binding="tns:BoxServiceSoapBinding">
			<soap:address location="http://localhost:9010/box" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
