
package com.example.boxservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BoxService", targetNamespace = "http://boxservice.example.com/", wsdlLocation = "http://localhost:9002/box?wsdl")
public class BoxService_Service
    extends Service
{

    private final static URL BOXSERVICE_WSDL_LOCATION;
    private final static WebServiceException BOXSERVICE_EXCEPTION;
    private final static QName BOXSERVICE_QNAME = new QName("http://boxservice.example.com/", "BoxService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9002/box?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BOXSERVICE_WSDL_LOCATION = url;
        BOXSERVICE_EXCEPTION = e;
    }

    public BoxService_Service() {
        super(__getWsdlLocation(), BOXSERVICE_QNAME);
    }

    public BoxService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), BOXSERVICE_QNAME, features);
    }

    public BoxService_Service(URL wsdlLocation) {
        super(wsdlLocation, BOXSERVICE_QNAME);
    }

    public BoxService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BOXSERVICE_QNAME, features);
    }

    public BoxService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BoxService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BoxService
     */
    @WebEndpoint(name = "BoxServiceEndpoint")
    public BoxService getBoxServiceEndpoint() {
        return super.getPort(new QName("http://boxservice.example.com/", "BoxServiceEndpoint"), BoxService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BoxService
     */
    @WebEndpoint(name = "BoxServiceEndpoint")
    public BoxService getBoxServiceEndpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://boxservice.example.com/", "BoxServiceEndpoint"), BoxService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BOXSERVICE_EXCEPTION!= null) {
            throw BOXSERVICE_EXCEPTION;
        }
        return BOXSERVICE_WSDL_LOCATION;
    }

}
