
package com.example.boxservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BoxService", targetNamespace = "http://boxservice.example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BoxService {


    /**
     * 
     * @param box
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "checkBoxFree", targetNamespace = "http://boxservice.example.com/", className = "com.example.boxservice.CheckBoxFree")
    @ResponseWrapper(localName = "checkBoxFreeResponse", targetNamespace = "http://boxservice.example.com/", className = "com.example.boxservice.CheckBoxFreeResponse")
    public boolean checkBoxFree(
        @WebParam(name = "box", targetNamespace = "")
        String box);

}
