
package com.example.carservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CarService", targetNamespace = "http://carservice.example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CarService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addCar", targetNamespace = "http://carservice.example.com/", className = "com.example.carservice.AddCar")
    @ResponseWrapper(localName = "addCarResponse", targetNamespace = "http://carservice.example.com/", className = "com.example.carservice.AddCarResponse")
    public void addCar(
        @WebParam(name = "arg0", targetNamespace = "")
        Car arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.carservice.Car
     * @throws NoSuchCarException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInformation", targetNamespace = "http://carservice.example.com/", className = "com.example.carservice.GetInformation")
    @ResponseWrapper(localName = "getInformationResponse", targetNamespace = "http://carservice.example.com/", className = "com.example.carservice.GetInformationResponse")
    public Car getInformation(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws NoSuchCarException_Exception
    ;

}
