
package com.example.carservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "NoSuchCarException", targetNamespace = "http://carservice.example.com/")
public class NoSuchCarException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NoSuchCarException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public NoSuchCarException_Exception(String message, NoSuchCarException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public NoSuchCarException_Exception(String message, NoSuchCarException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.example.carservice.NoSuchCarException
     */
    public NoSuchCarException getFaultInfo() {
        return faultInfo;
    }

}
